name: Scheduled Run

on:
  schedule:
  - cron: 27 6 * * 1-5
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test
