name: Scheduled Run

on:
  workflow_dispatch:
  schedule:
  - cron: 30 18 * * 1-5
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --logger "trx;LogFileName=TestResults.trx"
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.1
      id: trx-parser
      with:
        TRX_PATH: ${{ github.workspace }}/NunitTrelloTest/TestResults
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
